language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
  allow_failures:
    - os: osx

before_install: ./.travis/before_install.sh
install: ./.travis/install.sh
script: ./.travis/script.sh
