site_name: Adaptable Configuration Engine
theme: windmill
nav:
  - 'Home' : 'index.md'
  - 'Models' : 'models.md'
  - 'Types' : 'types.md'
  - 'Dependencies' : 'deps.md'
  - 'Code generation' : 'gen.md'
  - 'Miscellaneous' : 'misc.md'

extra:
  version: 1.2.0

markdown_extensions:
  - pymdownx.tasklist:
